In [2]:
import numpy as np

In [38]:
# criação de uma matriz de zeros, 3x3, do tipo int
m2 = np.zeros((5,5), dtype=int)

In [39]:
# dimensão da matriz
m2.ndim

2

In [40]:
print(m2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [41]:
# atribuição de valores aos elementos da matriz
for i in range(0,5):
    for j in range(0,5):
        m2[i][j] = i*j + j

In [42]:
print(m2)

[[ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]
 [ 0  5 10 15 20]]


In [43]:
# elemento (1,2) da matriz
m2[1][2]

4

In [44]:
# criação de uma matriz(tensor) de zeros, 3x4x5, com tipos float
n = 3
p = 4
q = 5
m3 = np.zeros((n,p,q), dtype=float)

In [45]:
m3.ndim

3

In [46]:
print(m3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [47]:
for i in range(0,n):
    for j in range(0,p):
        for k in range(0,q):
            m3[i][j][k] = i*n + j*p + k*q + i + j + k

In [48]:
print(m3)

[[[ 0.  6. 12. 18. 24.]
  [ 5. 11. 17. 23. 29.]
  [10. 16. 22. 28. 34.]
  [15. 21. 27. 33. 39.]]

 [[ 4. 10. 16. 22. 28.]
  [ 9. 15. 21. 27. 33.]
  [14. 20. 26. 32. 38.]
  [19. 25. 31. 37. 43.]]

 [[ 8. 14. 20. 26. 32.]
  [13. 19. 25. 31. 37.]
  [18. 24. 30. 36. 42.]
  [23. 29. 35. 41. 47.]]]


In [49]:
m3[1][2][3]

32.0